//
//  K.swift
//  Shelton
//
//  Created by Александр Иванов on 31.08.2021.
//

import Foundation

struct K {
    
    struct Items {
        static let goldenShield = Item(name: "Золотой щит", description: "Выглядит достаточно крепким", isWeapon: false, action: nil)
        static let silverDish = Item(name: "Серебряное блюдо", description: "Не блестит, а сверкает", isWeapon: false, action: 67)
        static let driedCrab = Item(name: "Сушеный краб", description: "Зачем старик-лодочник носил с собой сушеного краба? Может он просто старый безумец", isWeapon: false, action: nil)
        static let dolphinStatuette = Item(name: "Фигурка дельфина", description: "Довольно изящная работа, может кто-то её потерял?", isWeapon: false, action: 230)
        static let riderStatuette = Item(name: "Фигурка наездника", description: "Он явно должен сидеть на ком-то, но точно не на лошади", isWeapon: false, action: -55)
        static let bottleWithLetter = Item(name: "Бутылка с посланием", description: "Надеюсь, найдется тот, кому оно предназначено", isWeapon: false, action: nil)
        static let goldenRing = Item(name: "Золотой перстень", description: "Выглядит солидно, особенно на капитане", isWeapon: false, action: nil)
        static let horn = Item(name: "Рог рыбы-единорога", description: "Кажется, в него можно протрубить", isWeapon: false, action: -35)
        static let amulet = Item(name: "Амулет", description: "Исчезает после использования", isWeapon: false, action: nil)
        static let rustySword = Item(name: "Ржавый меч", description: "По крайней мере, не голыми руками", isWeapon: true, action: 248)
        static let swordFish = Item(name: "Рыба-пила", description: "Без понятия, почему её так называют. Может, она действительно умеет пилить?", isWeapon: false, action: nil)
        static let moonFish = Item(name: "Рыба-луна", description: "Красивая маленькая рыбка", isWeapon: false, action: nil)
        static let owlFeather = Item(name: "Перо филина", description: "С виду, перо как перо", isWeapon: false, action: nil)
        static let bell = Item(name: "Бубенчик", description: "Мило звенит", isWeapon: false, action: 267)
        static let rubyHoop = Item(name: "Обруч с рубином", description: "Сурову моряку врядли стоило его надевать...", isWeapon: false, action: -100)
        static let smoothPebble = Item(name: "Гладкий камешек", description: "В море много гладких камней. Но этот какой-то особенный", isWeapon: false, action: 376)
        static let sink = Item(name: "Раковина", description: "Просто прекрасная раковина", isWeapon: false, action: 271)
        static let crabClaw = Item(name: "Клешня краба", description: "Странная вещь... Зачем вообще таскать это с собой?", isWeapon: false, action: -269)
        static let trident = Item(name: "Трезубец", description: "Вполне пригодно для оружия", isWeapon: true, action: nil)
    }
    struct NPCs {
        static let plantKiller = NPC(name: "Растение-убийца", health: 2, attackStrenght: 8)
        static let seaDragon = NPC(name: "Морской дракончик", health: 8, attackStrenght: 9)
        static let spottedShark = NPC(name: "Пятнистая акула", health: 10, attackStrenght: 10)
        static let hedgehogFish = NPC(name: "Рыба-еж", health: 12, attackStrenght: 7)
        static let archer = NPC(name: "Брызгун", health: 9, attackStrenght: 8)
        static let shark = NPC(name: "Акула", health: 16, attackStrenght: 10)
        static let firstPirat = NPC(name: "Первый пират", health: 8, attackStrenght: 10)
        static let secondPirat = NPC(name: "Первый пират", health: 8, attackStrenght: 9)
        static let thirdPirat = NPC(name: "Первый пират", health: 8, attackStrenght: 10)
        static let captain = NPC(name: "Капитан", health: 14, attackStrenght: 10)
        static let firstWarrior = NPC(name: "Первый воин", health: 10, attackStrenght: 10)
        static let secondWarrior = NPC(name: "Второй воин", health: 10, attackStrenght: 10)
        static let rhinoceros = NPC(name: "Носорог", health: 8, attackStrenght: 10)
        static let knightOfTheWater = NPC(name: "Рыцарь-водяной", health: 12, attackStrenght: 9)
        static let kondor = NPC(name: "Кондор", health: 9, attackStrenght: 9)
        static let sailor = NPC(name: "Моряк", health: 12, attackStrenght: 10)
        static let octopus = NPC(name: "Спрут", health: 15, attackStrenght: 11)
        static let oldBoatman = NPC(name: "Старик-лодочник", health: 10, attackStrenght: 6)
        static let griff = NPC(name: "Гриф", health: 10, attackStrenght: 8)
        static let seaDeamon = NPC(name: "Морской черт", health: 2, attackStrenght: 9)
        static let wingedLion = NPC(name: "Крылатый лев", health: 8, attackStrenght: 10)
        static let giantCrab = NPC(name: "Гигантский краб", health: 14, attackStrenght: 9)
        static let seaKnight = NPC(name: "Морской рыцарь", health: 12, attackStrenght: 11)
        static let chameleonFish = NPC(name: "Рыба хамелеон", health: 10, attackStrenght: 8)
        static let seaSnake = NPC(name: "Морская змея", health: 11, attackStrenght: 14)
        static let fish = NPC(name: "Рыба", health: 9, attackStrenght: 8)
        static let warrior = NPC(name: "Воин", health: 14, attackStrenght: 11)
        static let giantSqid = NPC(name: "Гигантский кальмар", health: 14, attackStrenght: 11)
        static let firstMerman = NPC(name: "Первый водяной", health: 8, attackStrenght: 8)
        static let secondMerman = NPC(name: "Второй водяной", health: 9, attackStrenght: 7)
        static let electricSkat = NPC(name: "Электрический скат", health: 8, attackStrenght: 8)
        static let grumblerFish = NPC(name: "Рыба-ворчун", health: 7, attackStrenght: 6)
        static let giant = NPC(name: "Великан", health: 24, attackStrenght: 12)
        static let princeWarrior = NPC(name: "Воин Принца", health: 14, attackStrenght: 11)
        static let masterKnightOfTheWater = NPC(name: "Старший рыцарь-водяной", health: 10, attackStrenght: 9)
        static let firstKnightOfTheWater = NPC(name: "Первый рыцарь-водяной", health: 8, attackStrenght: 8)
        static let secondKnightOfTheWater = NPC(name: "Второй рыцарь-водяной", health: 9, attackStrenght: 7)
        static let thirdKnightOfTheWater = NPC(name: "Третий рыцарь-водяной", health: 9, attackStrenght: 7)
        static let dragon = NPC(name: "Дракон", health: 15, attackStrenght: 11)
        static let merman = NPC(name: "Водяной", health: 10, attackStrenght: 9)
        static let owl = NPC(name: "Филин", health: 9, attackStrenght: 9)
        static let cookMerman = NPC(name: "Повар-водяной", health: 8, attackStrenght: 8)
        static let dogFish = NPC(name: "Рыба-собака", health: 7, attackStrenght: 8)
        static let seaSpider = NPC(name: "Морской паук", health: 9, attackStrenght: 9)
        static let unicornFish = NPC(name: "Рыба-единорог", health: 8, attackStrenght: 10)
        static let nobleMan = NPC(name: "Дворянин", health: 12, attackStrenght: 10)
        static let hammerFish = NPC(name: "Рыба-молот", health: 8, attackStrenght: 9)
        static let electricEel = NPC(name: "Электрический угорь", health: 9, attackStrenght: 8)
        static let firstPiranha = NPC(name: "Первая пиранья", health: 10, attackStrenght: 10)
        static let secondPiranha = NPC(name: "Вторая пиранья", health: 10, attackStrenght: 10)
        static let seaNeedle = NPC(name: "Морская игла", health: 7, attackStrenght: 8)
        static let firstBarrakuda = NPC(name: "Первая барракуда", health: 15, attackStrenght: 11)
        static let secondBarrakuda = NPC(name: "Вторая барракуда", health: 15, attackStrenght: 11)
        static let manEater = NPC(name: "Акула-людоед", health: 11, attackStrenght: 9)
    }
}
